#include <gtest/gtest.h>
#include "loss.h"
#include <cmath>
#include <vector>
#include <fstream>
#include <string>
#include <cstdio>

// SimpleCase: 2x2 image, rendered=[1,0,0, 0,1,0, 0,0,1, 0.5,0.5,0.5], gt=all zeros.
// Verify loss=0.375, d_image signs correct.
TEST(L1Loss, SimpleCase) {
    const int H = 2, W = 2;
    const int n = H * W * 3; // 12
    float rendered[12] = {1,0,0, 0,1,0, 0,0,1, 0.5f,0.5f,0.5f};
    float gt[12] = {};
    float d_image[12] = {};

    float loss = l1_loss(rendered, gt, H, W, d_image);

    // sum of abs diffs = 1+0+0 + 0+1+0 + 0+0+1 + 0.5+0.5+0.5 = 4.5
    // mean = 4.5 / 12 = 0.375
    EXPECT_FLOAT_EQ(loss, 0.375f);

    float inv_n = 1.0f / 12.0f;
    // Where rendered > gt (positive diff), d_image = +inv_n
    EXPECT_FLOAT_EQ(d_image[0],  inv_n);  // 1 - 0 = +1
    EXPECT_FLOAT_EQ(d_image[1],  0.0f);   // 0 - 0 = 0
    EXPECT_FLOAT_EQ(d_image[2],  0.0f);   // 0 - 0 = 0
    EXPECT_FLOAT_EQ(d_image[3],  0.0f);   // 0 - 0 = 0
    EXPECT_FLOAT_EQ(d_image[4],  inv_n);  // 1 - 0 = +1
    EXPECT_FLOAT_EQ(d_image[5],  0.0f);
    EXPECT_FLOAT_EQ(d_image[6],  0.0f);
    EXPECT_FLOAT_EQ(d_image[7],  0.0f);
    EXPECT_FLOAT_EQ(d_image[8],  inv_n);  // 1 - 0 = +1
    EXPECT_FLOAT_EQ(d_image[9],  inv_n);  // 0.5 - 0 = +0.5
    EXPECT_FLOAT_EQ(d_image[10], inv_n);
    EXPECT_FLOAT_EQ(d_image[11], inv_n);
}

// PerfectMatch: Same image for rendered and gt. Verify loss=0.0, all d_image=0.0.
TEST(L1Loss, PerfectMatch) {
    const int H = 2, W = 2;
    float img[12] = {0.1f, 0.2f, 0.3f, 0.4f, 0.5f, 0.6f,
                     0.7f, 0.8f, 0.9f, 1.0f, 0.0f, 0.5f};
    float d_image[12] = {};

    float loss = l1_loss(img, img, H, W, d_image);

    EXPECT_FLOAT_EQ(loss, 0.0f);
    for (int i = 0; i < 12; i++) {
        EXPECT_FLOAT_EQ(d_image[i], 0.0f) << "d_image[" << i << "] != 0";
    }
}

// NegativeDiff: Rendered < gt. Verify d_image is negative.
TEST(L1Loss, NegativeDiff) {
    const int H = 1, W = 1;
    float rendered[3] = {0.0f, 0.1f, 0.2f};
    float gt[3]       = {1.0f, 0.5f, 0.9f};
    float d_image[3]  = {};

    float loss = l1_loss(rendered, gt, H, W, d_image);

    float inv_n = 1.0f / 3.0f;
    // All diffs negative => all d_image = -inv_n
    for (int i = 0; i < 3; i++) {
        EXPECT_FLOAT_EQ(d_image[i], -inv_n) << "d_image[" << i << "] should be negative";
    }

    // loss = (1.0 + 0.4 + 0.7) / 3 = 2.1 / 3 = 0.7
    EXPECT_NEAR(loss, 0.7f, 1e-6f);
}

// ============================================================
// Cross-language verification: C++ vs Python (serial float32)
// Data generated by: python harmonyos_3dgs/tools/verify_l1_loss.py
// ============================================================

// Use CMake-defined TEST_DATA_DIR for reliable path resolution
static std::string find_test_data_dir() {
    return std::string(TEST_DATA_DIR) + "/l1_verify";
}

static std::vector<float> read_bin(const std::string& path, int count) {
    std::vector<float> data(count);
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return {};
    size_t read = fread(data.data(), sizeof(float), count, f);
    fclose(f);
    if ((int)read != count) return {};
    return data;
}

struct L1TestCase {
    std::string name;
    int H, W;
    double py_loss_serial;  // Python serial accumulation (should match C++ exactly)
    double py_loss_numpy;   // Python numpy .mean() (may differ slightly)
};

// Parse a simple JSON manifest (no external JSON lib needed)
static std::vector<L1TestCase> parse_manifest(const std::string& path) {
    std::vector<L1TestCase> cases;
    std::ifstream f(path);
    if (!f.good()) return cases;
    std::string json((std::istreambuf_iterator<char>(f)),
                      std::istreambuf_iterator<char>());

    // Minimal parsing: find each object block
    size_t pos = 0;
    while ((pos = json.find("\"name\"", pos)) != std::string::npos) {
        L1TestCase tc;
        // name
        size_t q1 = json.find(':', pos) + 1;
        size_t q2 = json.find('"', q1) + 1;
        size_t q3 = json.find('"', q2);
        tc.name = json.substr(q2, q3 - q2);
        // H
        size_t hp = json.find("\"H\"", q3);
        size_t hv = json.find(':', hp) + 1;
        tc.H = std::stoi(json.substr(hv));
        // W
        size_t wp = json.find("\"W\"", hv);
        size_t wv = json.find(':', wp) + 1;
        tc.W = std::stoi(json.substr(wv));
        // loss_serial
        size_t ls = json.find("\"loss_serial\"", wv);
        size_t lsv = json.find(':', ls) + 1;
        tc.py_loss_serial = std::stod(json.substr(lsv));
        // loss_numpy
        size_t ln = json.find("\"loss_numpy\"", lsv);
        size_t lnv = json.find(':', ln) + 1;
        tc.py_loss_numpy = std::stod(json.substr(lnv));

        cases.push_back(tc);
        pos = q3 + 1;
    }
    return cases;
}

// Test: C++ L1 loss value matches Python serial accumulation exactly
TEST(L1LossCrosslang, LossValueMatchesPython) {
    std::string dir = find_test_data_dir();
    auto cases = parse_manifest(dir + "/manifest.json");
    ASSERT_FALSE(cases.empty()) << "No test cases found. Run: python harmonyos_3dgs/tools/verify_l1_loss.py";

    printf("\n  %-20s %10s %15s %15s %12s %6s\n",
           "Case", "Size", "C++ loss", "Python serial", "Abs diff", "Pass?");
    printf("  %-20s %10s %15s %15s %12s %6s\n",
           "----", "----", "--------", "-------------", "--------", "-----");

    int passed = 0;
    for (auto& tc : cases) {
        int n = tc.H * tc.W * 3;
        auto rendered = read_bin(dir + "/" + tc.name + "_rendered.bin", n);
        auto gt = read_bin(dir + "/" + tc.name + "_gt.bin", n);
        ASSERT_EQ((int)rendered.size(), n) << "Failed to read rendered data for " << tc.name;
        ASSERT_EQ((int)gt.size(), n) << "Failed to read gt data for " << tc.name;

        std::vector<float> d_image(n);
        float cpp_loss = l1_loss(rendered.data(), gt.data(), tc.H, tc.W, d_image.data());

        double abs_diff = std::abs((double)cpp_loss - tc.py_loss_serial);
        // C++ and Python both do serial float32 accumulation: should be bit-exact
        // Allow tiny tolerance for platform differences in float rounding
        bool pass = abs_diff < 1e-7;

        char size_str[32];
        snprintf(size_str, sizeof(size_str), "%dx%d", tc.H, tc.W);
        printf("  %-20s %10s %15.10f %15.10f %12.2e %6s\n",
               tc.name.c_str(), size_str, (double)cpp_loss, tc.py_loss_serial,
               abs_diff, pass ? "PASS" : "FAIL");

        EXPECT_TRUE(pass) << tc.name << ": C++=" << cpp_loss
                          << " Python=" << tc.py_loss_serial
                          << " diff=" << abs_diff;
        if (pass) passed++;
    }
    printf("  %d/%d passed\n", passed, (int)cases.size());
}

// Test: C++ gradient (d_image) matches Python gradient element-wise
TEST(L1LossCrosslang, GradientMatchesPython) {
    std::string dir = find_test_data_dir();
    auto cases = parse_manifest(dir + "/manifest.json");
    ASSERT_FALSE(cases.empty()) << "No test cases found. Run: python harmonyos_3dgs/tools/verify_l1_loss.py";

    for (auto& tc : cases) {
        int n = tc.H * tc.W * 3;
        auto rendered = read_bin(dir + "/" + tc.name + "_rendered.bin", n);
        auto gt = read_bin(dir + "/" + tc.name + "_gt.bin", n);
        auto py_d_image = read_bin(dir + "/" + tc.name + "_d_image.bin", n);
        ASSERT_EQ((int)py_d_image.size(), n) << "Failed to read gradient data for " << tc.name;

        std::vector<float> cpp_d_image(n);
        l1_loss(rendered.data(), gt.data(), tc.H, tc.W, cpp_d_image.data());

        int mismatches = 0;
        float max_diff = 0.0f;
        for (int i = 0; i < n; i++) {
            float diff = std::abs(cpp_d_image[i] - py_d_image[i]);
            if (diff > max_diff) max_diff = diff;
            if (diff > 1e-8f) mismatches++;
        }

        printf("  %-20s: grad max_diff=%.2e  mismatches=%d/%d\n",
               tc.name.c_str(), max_diff, mismatches, n);

        EXPECT_EQ(mismatches, 0) << tc.name << ": " << mismatches
                                 << " gradient mismatches, max_diff=" << max_diff;
    }
}
