// test_vk_vs_py_reference.cpp — VK vs Python autograd gradient comparison.
//
// Compares VulkanTrainer outputs against a pre-recorded Python reference dump
// (generated by tools/dump_tiny_reference.py) to validate that the Vulkan
// training pipeline matches PyTorch autograd numerically.
//
// Python reference dump layout (under tests/golden/tiny/py_ref/):
//   step_NNNN_loss.npy          -- scalar loss (L1, no DSSIM, no regs)
//   step_NNNN_grad_pos.npy      -- [N*3]  raw gradient for positions
//   step_NNNN_grad_sc.npy       -- [N*3]  raw gradient for scales
//   step_NNNN_grad_rot.npy      -- [N*4]  raw gradient for rotations
//   step_NNNN_grad_sh.npy       -- [N*max_coeffs*3] gradient for SH
//   step_NNNN_grad_op.npy       -- [N]    raw gradient for opacities
//   step_NNNN_raw_pos.npy       -- [N*3]  raw positions after Adam
//   step_NNNN_raw_sc.npy        -- [N*3]  raw scales after Adam
//   step_NNNN_raw_rot.npy       -- [N*4]  raw rotations after Adam
//   step_NNNN_raw_op.npy        -- [N]    raw opacities after Adam
//
// Fixture: tiny, N=20 Gaussians, SH degree 0, 64x64 image.
// HPs: pure L1, no densification, no DSSIM, SH locked to degree 0.
//
// GTEST_SKIP if no Vulkan device or Python dump is missing.

#include "vulkan_trainer.h"
#include "vulkan/vk_context.h"
#include "golden/npy_reader.h"
#include "train_types.h"
#include "types.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <vector>
#include <sstream>

namespace {

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

std::string tiny_cam0_dir() {
    return std::string(TEST_DATA_DIR) + "/../golden/tiny/step000001/cam0000";
}

std::string py_ref_dir() {
    return std::string(TEST_DATA_DIR) + "/../golden/tiny/py_ref";
}

bool py_ref_exists() {
    return std::filesystem::exists(py_ref_dir() + "/step_0001_loss.npy");
}

// ---------------------------------------------------------------------------
// NPY helpers
// ---------------------------------------------------------------------------

std::vector<float> npy_to_f32(const NpyArray& a) {
    assert_dtype(a, NpyDtype::float32);  // guard: silent corruption if dtype != float32
    std::vector<float> v(a.numel());
    std::memcpy(v.data(), a.raw.data(), a.numel() * sizeof(float));
    return v;
}

float npy_scalar(const std::string& path) {
    auto a = load_npy(path);
    std::vector<float> v = npy_to_f32(a);
    return v[0];
}

// ---------------------------------------------------------------------------
// Math helpers
// ---------------------------------------------------------------------------

float logit(float p) {
    p = std::max(1e-6f, std::min(1.0f - 1e-6f, p));
    return std::log(p / (1.0f - p));
}

float l2_norm(const std::vector<float>& v) {
    float acc = 0.0f;
    for (float x : v) acc += x * x;
    return std::sqrt(acc);
}

float l2_norm(const float* data, int n) {
    float acc = 0.0f;
    for (int i = 0; i < n; ++i) acc += data[i] * data[i];
    return std::sqrt(acc);
}

float rel_diff(float a, float b) {
    return std::fabs(a - b) / std::max(std::fabs(a), 1e-8f);
}

// ---------------------------------------------------------------------------
// Tiny fixture — matches pattern from test_cpu_vk_compare.cpp.
// N=20, SH degree 0, 64x64 image.
// ---------------------------------------------------------------------------

struct TinyScene {
    int N = 0, H = 0, W = 0;
    int sh_degree = 0, max_coeffs = 0;

    std::vector<float> positions, scales, rotations, opacities, sh_coeffs, filter_3d;
    std::vector<float> raw_positions, raw_scales, raw_rotations, raw_opacities, raw_sh;

    GaussianData      g{};
    RawGaussianParams raw{};
    Camera            cam{};
    RenderConfig      cfg{};

    bool load() {
        const std::string root = tiny_cam0_dir();
        try {
            auto pos = load_npy(root + "/input_positions.npy");
            auto scl = load_npy(root + "/input_scales.npy");
            auto rot = load_npy(root + "/input_rotations.npy");
            auto opa = load_npy(root + "/input_opacities.npy");
            auto sh  = load_npy(root + "/input_sh.npy");
            auto f3d = load_npy(root + "/input_filter_3D.npy");
            auto vm  = load_npy(root + "/input_viewmatrix.npy");
            auto pm  = load_npy(root + "/input_projmatrix.npy");
            auto fov = load_npy(root + "/input_fov_size.npy");
            auto cp  = load_npy(root + "/input_campos.npy");
            auto met = load_npy(root + "/input_meta.npy");

            sh_degree  = static_cast<int>(met.f32()[0]);
            max_coeffs = static_cast<int>(met.f32()[1]);
            H          = static_cast<int>(met.f32()[2]);
            W          = static_cast<int>(met.f32()[3]);
            N          = static_cast<int>(pos.shape[0]);

            positions = npy_to_f32(pos);
            scales    = npy_to_f32(scl);
            rotations = npy_to_f32(rot);
            opacities = npy_to_f32(opa);
            sh_coeffs = npy_to_f32(sh);
            filter_3d = npy_to_f32(f3d);

            // Activated → raw conversion
            raw_positions = positions;    // identity (no activation)
            raw_rotations = rotations;    // identity (normalize on-the-fly)
            raw_sh        = sh_coeffs;    // identity (no activation)

            raw_scales.resize(static_cast<size_t>(N) * 3);
            for (int i = 0; i < N * 3; ++i)
                raw_scales[static_cast<size_t>(i)] = std::log(scales[static_cast<size_t>(i)]);

            raw_opacities.resize(static_cast<size_t>(N));
            for (int i = 0; i < N; ++i)
                raw_opacities[static_cast<size_t>(i)] = logit(opacities[static_cast<size_t>(i)]);

            g.count      = N;  g.sh_degree  = sh_degree;  g.max_coeffs = max_coeffs;
            g.positions  = positions.data();   g.scales     = scales.data();
            g.rotations  = rotations.data();   g.opacities  = opacities.data();
            g.sh_coeffs  = sh_coeffs.data();   g.filter_3D  = filter_3d.data();

            raw.count         = N;  raw.sh_degree  = sh_degree;  raw.max_coeffs = max_coeffs;
            raw.raw_positions = raw_positions.data();  raw.raw_scales    = raw_scales.data();
            raw.raw_rotations = raw_rotations.data();  raw.raw_sh_coeffs = raw_sh.data();
            raw.raw_opacities = raw_opacities.data();

            std::memcpy(cam.view_matrix,     vm.f32(), 16 * sizeof(float));
            std::memcpy(cam.viewproj_matrix, pm.f32(), 16 * sizeof(float));
            cam.cam_pos[0] = cp.f32()[0];  cam.cam_pos[1] = cp.f32()[1];
            cam.cam_pos[2] = cp.f32()[2];
            cam.tan_fovx   = fov.f32()[0]; cam.tan_fovy   = fov.f32()[1];
            cam.width      = static_cast<int>(fov.f32()[2]);
            cam.height     = static_cast<int>(fov.f32()[3]);

            cfg.sh_degree      = sh_degree;  cfg.training       = true;
            cfg.eval_3D        = false;       cfg.tile_w         = 16;
            cfg.tile_h         = 16;          cfg.antialiasing   = false;
            cfg.scale_modifier = 1.0f;
            cfg.bg_color[0] = cfg.bg_color[1] = cfg.bg_color[2] = 0.0f;

            return true;
        } catch (...) {
            return false;
        }
    }
};

// Training config — must match Python dump's hyperparameters exactly.
VkTrainingConfig make_vk_tcfg() {
    VkTrainingConfig tcfg;
    tcfg.max_steps         = 30000;
    tcfg.pos_lr_init       = 1.6e-4f;
    tcfg.pos_lr_final      = 1.6e-6f;
    tcfg.sh_degree_max     = 0;        // lock SH degree to 0
    tcfg.sh_degree_warmup  = 100000;
    tcfg.lambda_dssim      = 0.0f;    // pure L1
    tcfg.opacity_reg       = 0.0f;
    tcfg.scale_reg         = 0.0f;
    tcfg.noise_lr          = 0.0f;
    tcfg.densify_from_step = 0;       // no densification
    return tcfg;
}

}  // namespace

// ---------------------------------------------------------------------------
// Test 1: Step1GradientAndLoss
//
// After exactly 1 step, compare:
//   - Loss against Python dump (< 1% rel_diff)
//   - Each gradient group L2 norm against Python dump (< 5% rel_diff)
//   - Each param group L2 norm after Adam against Python dump (< 1% rel_diff)
// ---------------------------------------------------------------------------

TEST(VkVsPyReference, Step1GradientAndLoss) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists()) GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    VkTrainingConfig tcfg = make_vk_tcfg();

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;  // lock SH degree to match Python dump

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, tcfg);
    trainer.enable_gradient_capture(true);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);

    // Run exactly 1 step.
    float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);

    ASSERT_FALSE(std::isnan(vk_loss)) << "VK loss is NaN after step 1";
    ASSERT_FALSE(std::isinf(vk_loss)) << "VK loss is Inf after step 1";

    // --- Load Python reference for step 1 ---
    const std::string pr = py_ref_dir();
    float py_loss = npy_scalar(pr + "/step_0001_loss.npy");

    auto py_grad_pos = npy_to_f32(load_npy(pr + "/step_0001_grad_pos.npy"));
    auto py_grad_sc  = npy_to_f32(load_npy(pr + "/step_0001_grad_sc.npy"));
    auto py_grad_rot = npy_to_f32(load_npy(pr + "/step_0001_grad_rot.npy"));
    auto py_grad_sh  = npy_to_f32(load_npy(pr + "/step_0001_grad_sh.npy"));
    auto py_grad_op  = npy_to_f32(load_npy(pr + "/step_0001_grad_op.npy"));

    auto py_raw_pos = npy_to_f32(load_npy(pr + "/step_0001_raw_pos.npy"));
    auto py_raw_sc  = npy_to_f32(load_npy(pr + "/step_0001_raw_sc.npy"));
    auto py_raw_rot = npy_to_f32(load_npy(pr + "/step_0001_raw_rot.npy"));
    auto py_raw_op  = npy_to_f32(load_npy(pr + "/step_0001_raw_op.npy"));

    // --- Loss comparison ---
    float loss_rd = rel_diff(py_loss, vk_loss);
    std::cout << "\n[Step 1 Loss]\n";
    std::cout << "  py_loss=" << py_loss << "  vk_loss=" << vk_loss
              << "  rel_diff=" << loss_rd << "\n";

    EXPECT_LT(loss_rd, 0.01f)
        << "Step-1 loss mismatch: Python=" << py_loss
        << " VK=" << vk_loss << " rel_diff=" << loss_rd;

    const int N = scene.N;

    // --- Gradient norm comparison ---
    const std::vector<float>& vk_grad_pos = trainer.captured_grad_positions();
    const std::vector<float>& vk_grad_sc  = trainer.captured_grad_scales();
    const std::vector<float>& vk_grad_rot = trainer.captured_grad_rotations();
    const std::vector<float>& vk_grad_sh  = trainer.captured_grad_sh();
    const std::vector<float>& vk_grad_op  = trainer.captured_grad_opacities();

    // Verify sizes match before norm comparison
    ASSERT_EQ(py_grad_pos.size(), trainer.captured_grad_positions().size())
        << "grad_pos size mismatch: N=" << N;
    ASSERT_EQ(py_grad_sc.size(), trainer.captured_grad_scales().size())
        << "grad_sc size mismatch: N=" << N;
    ASSERT_EQ(py_grad_rot.size(), trainer.captured_grad_rotations().size())
        << "grad_rot size mismatch";
    ASSERT_EQ(py_grad_sh.size(), trainer.captured_grad_sh().size())
        << "grad_sh size mismatch";
    ASSERT_EQ(py_grad_op.size(), trainer.captured_grad_opacities().size())
        << "grad_op size mismatch";

    struct GradGroup {
        const char* name;
        const std::vector<float>& py;
        const std::vector<float>& vk;
    };
    const GradGroup grad_groups[] = {
        { "positions", py_grad_pos, vk_grad_pos },
        { "scales",    py_grad_sc,  vk_grad_sc  },
        { "rotations", py_grad_rot, vk_grad_rot },
        { "sh",        py_grad_sh,  vk_grad_sh  },
        { "opacities", py_grad_op,  vk_grad_op  },
    };

    std::cout << "\n[Step 1 Gradient L2 norms]\n";
    std::cout << "Group       py_norm      vk_norm      rel_diff\n";
    std::cout << "----------  -----------  -----------  --------\n";
    for (const auto& gg : grad_groups) {
        float pn = l2_norm(gg.py);
        float vn = l2_norm(gg.vk);
        float rd = rel_diff(pn, vn);
        char buf[160];
        std::snprintf(buf, sizeof(buf), "%-10s  %.6e  %.6e  %.4f %s\n",
                      gg.name, pn, vn, rd, rd > 0.05f ? "MISMATCH" : "OK");
        std::cout << buf;
        EXPECT_LT(rd, 0.05f)
            << "Gradient " << gg.name << " norm mismatch: py=" << pn
            << " vk=" << vn << " rel_diff=" << rd;
    }

    // --- Post-Adam param norm comparison ---
    const RawGaussianParams& vk_p = trainer.raw_params();

    // Verify parameter sizes
    ASSERT_EQ(py_raw_pos.size(), static_cast<size_t>(N * 3)) << "py_raw_pos shape mismatch";
    ASSERT_EQ(py_raw_sc.size(),  static_cast<size_t>(N * 3)) << "py_raw_sc shape mismatch";
    ASSERT_EQ(py_raw_rot.size(), static_cast<size_t>(N * 4)) << "py_raw_rot shape mismatch";
    ASSERT_EQ(py_raw_op.size(),  static_cast<size_t>(N))     << "py_raw_op shape mismatch";

    struct ParamGroup {
        const char*   name;
        const std::vector<float>& py;
        const float*  vk;
        int           n;
    };
    const ParamGroup param_groups[] = {
        { "positions", py_raw_pos, vk_p.raw_positions, N * 3 },
        { "scales",    py_raw_sc,  vk_p.raw_scales,    N * 3 },
        { "rotations", py_raw_rot, vk_p.raw_rotations, N * 4 },
        { "opacities", py_raw_op,  vk_p.raw_opacities, N     },
    };

    std::cout << "\n[Step 1 Post-Adam Param L2 norms]\n";
    std::cout << "Group       py_norm      vk_norm      rel_diff\n";
    std::cout << "----------  -----------  -----------  --------\n";
    for (const auto& pg : param_groups) {
        float pn = l2_norm(pg.py);
        float vn = l2_norm(pg.vk, pg.n);
        float rd = rel_diff(pn, vn);
        char buf[160];
        std::snprintf(buf, sizeof(buf), "%-10s  %.6e  %.6e  %.4f %s\n",
                      pg.name, pn, vn, rd, rd > 0.01f ? "MISMATCH" : "OK");
        std::cout << buf;
        EXPECT_LT(rd, 0.01f)
            << "Param " << pg.name << " norm mismatch after step 1: py=" << pn
            << " vk=" << vn << " rel_diff=" << rd;
    }
}

// ---------------------------------------------------------------------------
// Test 2: ConvergenceTable100Steps
//
// Run VulkanTrainer for 100 steps. Assert:
//   (a) VK loss is finite and non-negative every step.
//   (b) Both VK and Python converge: loss at step 100 < 50% of step 1 loss.
//
// Per-step comparison table is printed for steps 1-10 and multiples of 10.
// Step-wise tolerance is NOT asserted — GPU/CPU FP accumulation diverges
// over many steps; this is expected and not a bug.
// ---------------------------------------------------------------------------

TEST(VkVsPyReference, ConvergenceTable100Steps) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists()) GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    constexpr int N_STEPS = 100;

    VkTrainingConfig tcfg = make_vk_tcfg();

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;  // lock SH degree to match Python dump

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, tcfg);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);

    std::vector<float> vk_losses(N_STEPS);
    std::vector<float> py_losses(N_STEPS);

    std::ostringstream log;
    log << "\nStep  py_loss      vk_loss      rel_diff\n";
    log << "----  -----------  -----------  --------\n";

    for (int s = 0; s < N_STEPS; ++s) {
        // Load Python loss for this step.
        char sname[256];
        std::snprintf(sname, sizeof(sname), "%s/step_%04d_loss.npy",
                      py_ref_dir().c_str(), s + 1);
        float py_loss = npy_scalar(sname);
        py_losses[static_cast<size_t>(s)] = py_loss;

        // Run VK step.
        float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);
        vk_losses[static_cast<size_t>(s)] = vk_loss;

        // (a) VK must never produce NaN/Inf/negative.
        ASSERT_FALSE(std::isnan(vk_loss)) << "VK loss is NaN at step " << (s + 1);
        ASSERT_FALSE(std::isinf(vk_loss)) << "VK loss is Inf at step " << (s + 1);
        ASSERT_GE(vk_loss, 0.0f)          << "VK loss negative at step " << (s + 1);

        // Print rows: steps 1-10 and every multiple of 10.
        if (s < 10 || (s + 1) % 10 == 0) {
            float rd = rel_diff(py_loss, vk_loss);
            char buf[128];
            std::snprintf(buf, sizeof(buf), "%4d  %.6e  %.6e  %.4f\n",
                          s + 1, py_loss, vk_loss, rd);
            log << buf;
        }
    }
    std::cout << log.str() << "\n";

    // (b) Both must converge: loss at step 100 < 50% of step 1 loss.
    EXPECT_LT(py_losses[N_STEPS - 1], py_losses[0] * 0.5f)
        << "Python did not converge in 100 steps: init=" << py_losses[0]
        << " final=" << py_losses[N_STEPS - 1];
    EXPECT_LT(vk_losses[N_STEPS - 1], vk_losses[0] * 0.5f)
        << "VK did not converge in 100 steps: init=" << vk_losses[0]
        << " final=" << vk_losses[N_STEPS - 1];
}

// ---------------------------------------------------------------------------
// Test 3: PerStepFullComparison
//
// Run 100 VK steps with gradient capture. At every step, compare loss,
// per-group gradient L2 norms, and per-group parameter L2 norms against
// the Python reference dump.
//
// Design: comparing norms (not element-wise) tolerates unavoidable FP
// accumulation from independent GPU/CPU floating-point evaluation order
// while still catching wrong formulas (which show up as large norm errors).
//
// Tolerances:
//   - Grad norms  < 20% max over 100 steps  (catches wrong sign/formula)
//   - Param norms < 10% max over 100 steps  (tighter: Adam state compounds)
//
// Loss rel_diff is printed per step but not asserted here (already covered
// by ConvergenceTable100Steps).
// ---------------------------------------------------------------------------

TEST(VkVsPyReference, PerStepFullComparison) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists())
        GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    constexpr int N_STEPS = 100;

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, make_vk_tcfg());
    trainer.enable_gradient_capture(true);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);
    const int N   = scene.N;
    const int MC3 = scene.max_coeffs * 3;

    // Max divergences across all steps (for final assertions).
    float max_loss_rd    = 0.0f;
    float max_gpos_rd    = 0.0f, max_gsc_rd  = 0.0f;
    float max_grot_rd    = 0.0f, max_gsh_rd  = 0.0f, max_gop_rd = 0.0f;
    float max_ppos_rd    = 0.0f, max_psc_rd  = 0.0f;
    float max_prot_rd    = 0.0f, max_pop_rd  = 0.0f;

    std::cout << "\n=== 100-step full comparison: loss + grad norms + param norms ===\n";
    std::cout << "Step  loss%  gpos%  gsc%  grot%  gsh%  gop%  ppos%  psc%  prot%  pop%\n";
    std::cout << "----  -----  -----  ----  -----  ----  ----  -----  ----  -----  ----\n";

    for (int s = 0; s < N_STEPS; ++s) {
        const int step = s + 1;
        char pref[256];
        std::snprintf(pref, sizeof(pref), "%s/step_%04d",
                      py_ref_dir().c_str(), step);

        const std::string sp(pref);
        float py_loss    = npy_scalar(sp + "_loss.npy");
        auto  py_gpos    = npy_to_f32(load_npy(sp + "_grad_pos.npy"));
        auto  py_gsc     = npy_to_f32(load_npy(sp + "_grad_sc.npy"));
        auto  py_grot    = npy_to_f32(load_npy(sp + "_grad_rot.npy"));
        auto  py_gsh     = npy_to_f32(load_npy(sp + "_grad_sh.npy"));
        auto  py_gop     = npy_to_f32(load_npy(sp + "_grad_op.npy"));
        auto  py_rpos    = npy_to_f32(load_npy(sp + "_raw_pos.npy"));
        auto  py_rsc     = npy_to_f32(load_npy(sp + "_raw_sc.npy"));
        auto  py_rrot    = npy_to_f32(load_npy(sp + "_raw_rot.npy"));
        auto  py_rop     = npy_to_f32(load_npy(sp + "_raw_op.npy"));

        float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);

        ASSERT_FALSE(std::isnan(vk_loss)) << "VK NaN at step " << step;
        ASSERT_FALSE(std::isinf(vk_loss)) << "VK Inf at step " << step;

        // Gradient norm divergences (VK vs Python, after regularization, before Adam).
        float loss_rd = rel_diff(vk_loss, py_loss);
        float gpos_rd = rel_diff(l2_norm(trainer.captured_grad_positions().data(), N * 3),
                                 l2_norm(py_gpos));
        float gsc_rd  = rel_diff(l2_norm(trainer.captured_grad_scales().data(),    N * 3),
                                 l2_norm(py_gsc));
        float grot_rd = rel_diff(l2_norm(trainer.captured_grad_rotations().data(), N * 4),
                                 l2_norm(py_grot));
        float gsh_rd  = rel_diff(l2_norm(trainer.captured_grad_sh().data(),        N * MC3),
                                 l2_norm(py_gsh));
        float gop_rd  = rel_diff(l2_norm(trainer.captured_grad_opacities().data(), N),
                                 l2_norm(py_gop));

        // Parameter norm divergences (after Adam step).
        const RawGaussianParams& vk_p = trainer.raw_params();
        float ppos_rd = rel_diff(l2_norm(vk_p.raw_positions, N * 3), l2_norm(py_rpos));
        float psc_rd  = rel_diff(l2_norm(vk_p.raw_scales,    N * 3), l2_norm(py_rsc));
        float prot_rd = rel_diff(l2_norm(vk_p.raw_rotations, N * 4), l2_norm(py_rrot));
        float pop_rd  = rel_diff(l2_norm(vk_p.raw_opacities, N),     l2_norm(py_rop));

        max_loss_rd  = std::max(max_loss_rd,  loss_rd);
        max_gpos_rd  = std::max(max_gpos_rd,  gpos_rd);
        max_gsc_rd   = std::max(max_gsc_rd,   gsc_rd);
        max_grot_rd  = std::max(max_grot_rd,  grot_rd);
        max_gsh_rd   = std::max(max_gsh_rd,   gsh_rd);
        max_gop_rd   = std::max(max_gop_rd,   gop_rd);
        max_ppos_rd  = std::max(max_ppos_rd,  ppos_rd);
        max_psc_rd   = std::max(max_psc_rd,   psc_rd);
        max_prot_rd  = std::max(max_prot_rd,  prot_rd);
        max_pop_rd   = std::max(max_pop_rd,   pop_rd);

        if (step <= 10 || step % 10 == 0) {
            char buf[256];
            std::snprintf(buf, sizeof(buf),
                "%4d  %4.2f%%  %4.2f%%  %3.2f%%  %4.2f%%  %3.2f%%  %3.2f%%  "
                "%4.2f%%  %3.2f%%  %4.2f%%  %3.2f%%\n",
                step,
                loss_rd * 100.f, gpos_rd * 100.f, gsc_rd * 100.f,
                grot_rd * 100.f, gsh_rd * 100.f,  gop_rd * 100.f,
                ppos_rd * 100.f, psc_rd * 100.f,  prot_rd * 100.f, pop_rd * 100.f);
            std::cout << buf;
        }
    }

    std::cout << "\n=== Max divergence across 100 steps ===\n";
    char sbuf[512];
    std::snprintf(sbuf, sizeof(sbuf),
        "  loss:      %.3f%%\n"
        "  grad_pos:  %.3f%%  grad_sc: %.3f%%  grad_rot: %.3f%%\n"
        "  grad_sh:   %.3f%%  grad_op: %.3f%%\n"
        "  param_pos: %.3f%%  param_sc: %.3f%%  param_rot: %.3f%%  param_op: %.3f%%\n",
        max_loss_rd * 100.f,
        max_gpos_rd * 100.f, max_gsc_rd * 100.f, max_grot_rd * 100.f,
        max_gsh_rd * 100.f,  max_gop_rd * 100.f,
        max_ppos_rd * 100.f, max_psc_rd * 100.f,
        max_prot_rd * 100.f, max_pop_rd * 100.f);
    std::cout << sbuf;

    EXPECT_LT(max_gpos_rd, 0.20f) << "grad_pos max norm divergence > 20%";
    EXPECT_LT(max_gsc_rd,  0.20f) << "grad_sc max norm divergence > 20%";
    EXPECT_LT(max_grot_rd, 0.20f) << "grad_rot max norm divergence > 20%";
    EXPECT_LT(max_gsh_rd,  0.20f) << "grad_sh max norm divergence > 20%";
    EXPECT_LT(max_gop_rd,  0.20f) << "grad_op max norm divergence > 20%";
    EXPECT_LT(max_ppos_rd, 0.10f) << "param_pos max norm divergence > 10%";
    EXPECT_LT(max_psc_rd,  0.10f) << "param_sc max norm divergence > 10%";
    EXPECT_LT(max_prot_rd, 0.10f) << "param_rot max norm divergence > 10%";
    EXPECT_LT(max_pop_rd,  0.10f) << "param_op max norm divergence > 10%";
}

// ---------------------------------------------------------------------------
// Test 4: OraclePerStepComparison
//
// For each step i in [1..100], inject Python step i-1 params into a freshly
// zeroed VulkanTrainer, run 1 step, and compare loss and gradients element-wise
// against Python step i.
//
// This approach removes FP-accumulation as a confound: every oracle step starts
// from IDENTICAL inputs to Python. If the algorithm is correct, loss and
// gradients must match to within single-step FP precision (same as step 1).
//
// NOTE: params AFTER Adam are NOT compared here because oracle uses freshly
// zeroed Adam state while Python has accumulated moments from previous steps.
// Adam correctness is proven at step 1 by Step1GradientAndLoss.
// ---------------------------------------------------------------------------
TEST(VkVsPyReference, OraclePerStepComparison) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists())
        GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    constexpr int N_STEPS = 100;

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, make_vk_tcfg());
    trainer.enable_gradient_capture(true);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);
    const int N   = scene.N;
    const int MC3 = scene.max_coeffs * 3;

    // Helper: max element-wise relative diff.
    // Denominator = max(|py[i]|, 1e-3 × ||py||_inf) to avoid inflating relative
    // error for near-zero elements. Without the group-relative floor, an element
    // at py=1e-8 with absolute diff 6e-11 (pure FP noise) would read as 0.6% —
    // a measurement artifact that obscures real errors on larger elements.
    auto max_elem_rel_diff = [](const float* vk, const float* py, int n) -> float {
        float py_inf = 0.0f;
        for (int i = 0; i < n; ++i) py_inf = std::max(py_inf, std::fabs(py[i]));
        const float floor_denom = 1e-3f * std::max(py_inf, 1e-8f);
        float mx = 0.0f;
        for (int i = 0; i < n; ++i) {
            float d = std::fabs(vk[i] - py[i]) / std::max(std::fabs(py[i]), floor_denom);
            mx = std::max(mx, d);
        }
        return mx;
    };

    // Storage for the "previous step" raw params (loaded from Python dump).
    std::vector<float> prev_pos, prev_sc, prev_rot, prev_sh, prev_op;

    float max_loss_rd_all = 0.0f, max_grad_rd_all = 0.0f;
    int   worst_step_loss = 0,    worst_step_grad = 0;

    bool all_pass = true;

    std::cout << "\n=== Oracle per-step comparison (injected Python params, fresh Adam) ===\n";
    std::cout << "Step  loss_rd%  gpos_mrd%  gsc_mrd%  grot_mrd%  gsh_mrd%  gop_mrd%\n";
    std::cout << "----  --------  ---------  --------  ---------  --------  --------\n";

    for (int s = 0; s < N_STEPS; ++s) {
        const int step = s + 1;    // Python dump step index (1-based)
        const int prev = s;        // Python dump step index of previous step (0 = initial)

        // Load previous-step params.
        if (prev == 0) {
            // Step 0: use fixture initial params.
            prev_pos.assign(scene.raw_positions.begin(), scene.raw_positions.end());
            prev_sc .assign(scene.raw_scales.begin(),    scene.raw_scales.end());
            prev_rot.assign(scene.raw_rotations.begin(), scene.raw_rotations.end());
            prev_sh .assign(scene.raw_sh.begin(),        scene.raw_sh.end());
            prev_op .assign(scene.raw_opacities.begin(), scene.raw_opacities.end());
        } else {
            char pp[256];
            std::snprintf(pp, sizeof(pp), "%s/step_%04d", py_ref_dir().c_str(), prev);
            const std::string spp(pp);
            prev_pos = npy_to_f32(load_npy(spp + "_raw_pos.npy"));
            prev_sc  = npy_to_f32(load_npy(spp + "_raw_sc.npy"));
            prev_rot = npy_to_f32(load_npy(spp + "_raw_rot.npy"));
            prev_sh  = npy_to_f32(load_npy(spp + "_raw_sh.npy"));
            prev_op  = npy_to_f32(load_npy(spp + "_raw_op.npy"));
        }

        // Build RawGaussianParams pointing into the loaded vectors.
        RawGaussianParams oracle_raw{};
        oracle_raw.count         = N;
        oracle_raw.sh_degree     = scene.sh_degree;
        oracle_raw.max_coeffs    = scene.max_coeffs;
        oracle_raw.raw_positions = prev_pos.data();
        oracle_raw.raw_scales    = prev_sc.data();
        oracle_raw.raw_rotations = prev_rot.data();
        oracle_raw.raw_sh_coeffs = prev_sh.data();
        oracle_raw.raw_opacities = prev_op.data();

        // Inject params + zero Adam + reset step_count.
        trainer.reset_for_oracle(oracle_raw);

        // Run one VK step.
        float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);
        ASSERT_FALSE(std::isnan(vk_loss)) << "VK NaN at oracle step " << step;
        ASSERT_FALSE(std::isinf(vk_loss)) << "VK Inf at oracle step " << step;

        // Load Python reference for this step.
        char sp[256];
        std::snprintf(sp, sizeof(sp), "%s/step_%04d", py_ref_dir().c_str(), step);
        const std::string ssp(sp);
        float py_loss  = npy_scalar(ssp + "_loss.npy");
        auto  py_gpos  = npy_to_f32(load_npy(ssp + "_grad_pos.npy"));
        auto  py_gsc   = npy_to_f32(load_npy(ssp + "_grad_sc.npy"));
        auto  py_grot  = npy_to_f32(load_npy(ssp + "_grad_rot.npy"));
        auto  py_gsh   = npy_to_f32(load_npy(ssp + "_grad_sh.npy"));
        auto  py_gop   = npy_to_f32(load_npy(ssp + "_grad_op.npy"));

        // Element-wise max relative differences.
        float loss_rd = rel_diff(vk_loss, py_loss);
        float gpos_rd = max_elem_rel_diff(trainer.captured_grad_positions().data(),
                                          py_gpos.data(), N * 3);
        float gsc_rd  = max_elem_rel_diff(trainer.captured_grad_scales().data(),
                                          py_gsc.data(), N * 3);
        float grot_rd = max_elem_rel_diff(trainer.captured_grad_rotations().data(),
                                          py_grot.data(), N * 4);
        float gsh_rd  = max_elem_rel_diff(trainer.captured_grad_sh().data(),
                                          py_gsh.data(), N * MC3);
        float gop_rd  = max_elem_rel_diff(trainer.captured_grad_opacities().data(),
                                          py_gop.data(), N);
        // Per-group max element-wise rel-diff tracking.
        // Thresholds set at ~2× the empirically measured maxima (2026-04-20),
        // using group-relative denominator (floor = 1e-3 × group_inf_norm):
        //   loss: 0.0003%  → threshold 0.001%   (3× headroom)
        //   gpos: 0.1049%  → threshold 0.20%    (2× headroom; GPU parallel-reduce on small N)
        //   gsc:  0.0002%  → threshold 0.01%    (50× headroom)
        //   grot: 0.0408%  → threshold 0.10%    (2.5× headroom; quat Jacobian cross-terms)
        //   gsh:  0.0001%  → threshold 0.01%
        //   gop:  0.0001%  → threshold 0.01%
        float grad_max_rd = std::max({gpos_rd, gsc_rd, grot_rd, gsh_rd, gop_rd});

        if (loss_rd    > max_loss_rd_all) { max_loss_rd_all = loss_rd;    worst_step_loss = step; }
        if (grad_max_rd > max_grad_rd_all) { max_grad_rd_all = grad_max_rd; worst_step_grad = step; }

        bool step_pass = (loss_rd  < 0.00001f) &&   // 0.001%
                         (gpos_rd  < 0.002f)   &&   // 0.20%
                         (gsc_rd   < 0.0001f)  &&   // 0.01%
                         (grot_rd  < 0.001f)   &&   // 0.10%
                         (gsh_rd   < 0.0001f)  &&   // 0.01%
                         (gop_rd   < 0.0001f);      // 0.01%
        if (!step_pass) all_pass = false;

        // Print every step (verbose — full oracle table).
        char buf[256];
        std::snprintf(buf, sizeof(buf),
            "%4d  %7.4f%%  %8.4f%%  %7.4f%%  %8.4f%%  %7.4f%%  %7.4f%%  %s\n",
            step,
            loss_rd * 100.f, gpos_rd * 100.f, gsc_rd * 100.f,
            grot_rd * 100.f, gsh_rd * 100.f,  gop_rd * 100.f,
            step_pass ? "" : "FAIL");
        std::cout << buf;
    }

    std::cout << "\n=== Oracle summary ===\n";
    char sbuf[512];
    std::snprintf(sbuf, sizeof(sbuf),
        "  Max loss rel_diff:      %.4f%% (step %d)  [thresh 0.001%%]\n"
        "  Max grad max_elem_diff: %.4f%% (step %d)  [thresh per-group: pos<0.20%% sc<0.01%% rot<0.10%% sh<0.01%% op<0.01%%]\n"
        "  All steps pass: %s\n",
        max_loss_rd_all * 100.f, worst_step_loss,
        max_grad_rd_all * 100.f, worst_step_grad,
        all_pass ? "YES" : "NO");
    std::cout << sbuf;

    EXPECT_LT(max_loss_rd_all, 0.00001f)
        << "Oracle max loss rel_diff > 0.001% (worst: step " << worst_step_loss << ")";
    EXPECT_LT(max_grad_rd_all, 0.002f)
        << "Oracle max gradient element rel_diff > 0.20% (worst: step " << worst_step_grad << ")";
}

// ---------------------------------------------------------------------------
// Diagnostic: element-wise print for worst grot/gpos steps
// ---------------------------------------------------------------------------
TEST(VkVsPyReference, DiagnosticElemwiseWorstSteps) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists())
        GTEST_SKIP() << "Python dump missing.";

    TinyScene scene;
    ASSERT_TRUE(scene.load());

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, make_vk_tcfg());
    trainer.enable_gradient_capture(true);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);
    const int N    = scene.N;
    const int MC3  = scene.max_coeffs * 3;

    // Diagnose step 61 grot and step 98 gpos.
    struct Job { int prev; int step; const char* group; };
    for (auto [prev_s, step_s, grp] : std::vector<Job>{{60,61,"grot"},{97,98,"gpos"}}) {
        // Load prev params.
        auto load_prev = [&](int ps) {
            std::vector<float> pos, sc, rot, sh, op;
            if (ps == 0) {
                pos = scene.raw_positions; sc = scene.raw_scales;
                rot = scene.raw_rotations; sh  = scene.raw_sh;
                op  = scene.raw_opacities;
            } else {
                char pp[256];
                std::snprintf(pp, sizeof(pp), "%s/step_%04d", py_ref_dir().c_str(), ps);
                pos = npy_to_f32(load_npy(std::string(pp) + "_raw_pos.npy"));
                sc  = npy_to_f32(load_npy(std::string(pp) + "_raw_sc.npy"));
                rot = npy_to_f32(load_npy(std::string(pp) + "_raw_rot.npy"));
                sh  = npy_to_f32(load_npy(std::string(pp) + "_raw_sh.npy"));
                op  = npy_to_f32(load_npy(std::string(pp) + "_raw_op.npy"));
            }
            return std::make_tuple(pos, sc, rot, sh, op);
        };

        auto [pos, sc, rot, sh, op] = load_prev(prev_s);
        RawGaussianParams oracle_raw{};
        oracle_raw.count = N; oracle_raw.sh_degree = scene.sh_degree;
        oracle_raw.max_coeffs = scene.max_coeffs;
        oracle_raw.raw_positions = pos.data(); oracle_raw.raw_scales = sc.data();
        oracle_raw.raw_rotations = rot.data(); oracle_raw.raw_sh_coeffs = sh.data();
        oracle_raw.raw_opacities = op.data();
        trainer.reset_for_oracle(oracle_raw);
        float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);

        // Load Python reference grads.
        char sp[256];
        std::snprintf(sp, sizeof(sp), "%s/step_%04d", py_ref_dir().c_str(), step_s);
        std::string ssp(sp);
        std::vector<float> py_g, vk_g;
        int elem_size = 0;
        if (std::string(grp) == "grot") {
            py_g = npy_to_f32(load_npy(ssp + "_grad_rot.npy"));
            vk_g = trainer.captured_grad_rotations();
            elem_size = N * 4;
        } else {
            py_g = npy_to_f32(load_npy(ssp + "_grad_pos.npy"));
            vk_g = trainer.captured_grad_positions();
            elem_size = N * 3;
        }

        printf("\n=== step %d %s element-wise (py vs vk) ===\n", step_s, grp);
        printf("%4s  %5s  %14s  %14s  %10s  %8s\n",
               "idx","G.c","py","vk","abs_diff","rel_diff%");
        float max_rd = 0.f; int worst_i = -1;
        for (int i = 0; i < elem_size; ++i) {
            float denom = std::max(std::fabs(py_g[i]), 1e-8f);
            float ad = std::fabs(vk_g[i] - py_g[i]);
            float rd = ad / denom;
            if (rd > max_rd) { max_rd = rd; worst_i = i; }
        }
        // Print worst 15 elements by rel_diff.
        std::vector<std::pair<float,int>> ranked;
        for (int i = 0; i < elem_size; ++i) {
            float denom = std::max(std::fabs(py_g[i]), 1e-8f);
            ranked.push_back({std::fabs(vk_g[i]-py_g[i])/denom, i});
        }
        std::sort(ranked.begin(), ranked.end(), [](auto& a, auto& b){ return a.first > b.first; });
        int stride = (std::string(grp) == "grot") ? 4 : 3;
        for (int k = 0; k < std::min(15, (int)ranked.size()); ++k) {
            int i = ranked[k].second;
            float denom = std::max(std::fabs(py_g[i]), 1e-8f);
            float ad = std::fabs(vk_g[i] - py_g[i]);
            float rd = ad / denom;
            printf("%4d  %2d.%1d  %+14.6e  %+14.6e  %10.4e  %8.4f%%\n",
                   i, i/stride, i%stride,
                   py_g[i], vk_g[i], ad, rd*100.f);
        }
        printf("  max rel_diff=%.4f%% at idx %d\n", max_rd*100.f, worst_i);
    }
    SUCCEED();
}
