// test_vk_vs_py_reference.cpp — VK vs Python autograd gradient comparison.
//
// Compares VulkanTrainer outputs against a pre-recorded Python reference dump
// (generated by tools/dump_tiny_reference.py) to validate that the Vulkan
// training pipeline matches PyTorch autograd numerically.
//
// Python reference dump layout (under tests/golden/tiny/py_ref/):
//   step_NNNN_loss.npy          -- scalar loss (L1, no DSSIM, no regs)
//   step_NNNN_grad_pos.npy      -- [N*3]  raw gradient for positions
//   step_NNNN_grad_sc.npy       -- [N*3]  raw gradient for scales
//   step_NNNN_grad_rot.npy      -- [N*4]  raw gradient for rotations
//   step_NNNN_grad_sh.npy       -- [N*max_coeffs*3] gradient for SH
//   step_NNNN_grad_op.npy       -- [N]    raw gradient for opacities
//   step_NNNN_raw_pos.npy       -- [N*3]  raw positions after Adam
//   step_NNNN_raw_sc.npy        -- [N*3]  raw scales after Adam
//   step_NNNN_raw_rot.npy       -- [N*4]  raw rotations after Adam
//   step_NNNN_raw_op.npy        -- [N]    raw opacities after Adam
//
// Fixture: tiny, N=20 Gaussians, SH degree 0, 64x64 image.
// HPs: pure L1, no densification, no DSSIM, SH locked to degree 0.
//
// GTEST_SKIP if no Vulkan device or Python dump is missing.

#include "vulkan_trainer.h"
#include "vulkan/vk_context.h"
#include "golden/npy_reader.h"
#include "train_types.h"
#include "types.h"

#include <gtest/gtest.h>

#include <cmath>
#include <cstring>
#include <filesystem>
#include <vector>
#include <sstream>

namespace {

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

std::string tiny_cam0_dir() {
    return std::string(TEST_DATA_DIR) + "/../golden/tiny/step000001/cam0000";
}

std::string py_ref_dir() {
    return std::string(TEST_DATA_DIR) + "/../golden/tiny/py_ref";
}

bool py_ref_exists() {
    return std::filesystem::exists(py_ref_dir() + "/step_0001_loss.npy");
}

// ---------------------------------------------------------------------------
// NPY helpers
// ---------------------------------------------------------------------------

std::vector<float> npy_to_f32(const NpyArray& a) {
    assert_dtype(a, NpyDtype::float32);  // guard: silent corruption if dtype != float32
    std::vector<float> v(a.numel());
    std::memcpy(v.data(), a.raw.data(), a.numel() * sizeof(float));
    return v;
}

float npy_scalar(const std::string& path) {
    auto a = load_npy(path);
    std::vector<float> v = npy_to_f32(a);
    return v[0];
}

// ---------------------------------------------------------------------------
// Math helpers
// ---------------------------------------------------------------------------

float logit(float p) {
    p = std::max(1e-6f, std::min(1.0f - 1e-6f, p));
    return std::log(p / (1.0f - p));
}

float l2_norm(const std::vector<float>& v) {
    float acc = 0.0f;
    for (float x : v) acc += x * x;
    return std::sqrt(acc);
}

float l2_norm(const float* data, int n) {
    float acc = 0.0f;
    for (int i = 0; i < n; ++i) acc += data[i] * data[i];
    return std::sqrt(acc);
}

float rel_diff(float a, float b) {
    return std::fabs(a - b) / std::max(std::fabs(a), 1e-8f);
}

// ---------------------------------------------------------------------------
// Tiny fixture — matches pattern from test_cpu_vk_compare.cpp.
// N=20, SH degree 0, 64x64 image.
// ---------------------------------------------------------------------------

struct TinyScene {
    int N = 0, H = 0, W = 0;
    int sh_degree = 0, max_coeffs = 0;

    std::vector<float> positions, scales, rotations, opacities, sh_coeffs, filter_3d;
    std::vector<float> raw_positions, raw_scales, raw_rotations, raw_opacities, raw_sh;

    GaussianData      g{};
    RawGaussianParams raw{};
    Camera            cam{};
    RenderConfig      cfg{};

    bool load() {
        const std::string root = tiny_cam0_dir();
        try {
            auto pos = load_npy(root + "/input_positions.npy");
            auto scl = load_npy(root + "/input_scales.npy");
            auto rot = load_npy(root + "/input_rotations.npy");
            auto opa = load_npy(root + "/input_opacities.npy");
            auto sh  = load_npy(root + "/input_sh.npy");
            auto f3d = load_npy(root + "/input_filter_3D.npy");
            auto vm  = load_npy(root + "/input_viewmatrix.npy");
            auto pm  = load_npy(root + "/input_projmatrix.npy");
            auto fov = load_npy(root + "/input_fov_size.npy");
            auto cp  = load_npy(root + "/input_campos.npy");
            auto met = load_npy(root + "/input_meta.npy");

            sh_degree  = static_cast<int>(met.f32()[0]);
            max_coeffs = static_cast<int>(met.f32()[1]);
            H          = static_cast<int>(met.f32()[2]);
            W          = static_cast<int>(met.f32()[3]);
            N          = static_cast<int>(pos.shape[0]);

            positions = npy_to_f32(pos);
            scales    = npy_to_f32(scl);
            rotations = npy_to_f32(rot);
            opacities = npy_to_f32(opa);
            sh_coeffs = npy_to_f32(sh);
            filter_3d = npy_to_f32(f3d);

            // Activated → raw conversion
            raw_positions = positions;    // identity (no activation)
            raw_rotations = rotations;    // identity (normalize on-the-fly)
            raw_sh        = sh_coeffs;    // identity (no activation)

            raw_scales.resize(static_cast<size_t>(N) * 3);
            for (int i = 0; i < N * 3; ++i)
                raw_scales[static_cast<size_t>(i)] = std::log(scales[static_cast<size_t>(i)]);

            raw_opacities.resize(static_cast<size_t>(N));
            for (int i = 0; i < N; ++i)
                raw_opacities[static_cast<size_t>(i)] = logit(opacities[static_cast<size_t>(i)]);

            g.count      = N;  g.sh_degree  = sh_degree;  g.max_coeffs = max_coeffs;
            g.positions  = positions.data();   g.scales     = scales.data();
            g.rotations  = rotations.data();   g.opacities  = opacities.data();
            g.sh_coeffs  = sh_coeffs.data();   g.filter_3D  = filter_3d.data();

            raw.count         = N;  raw.sh_degree  = sh_degree;  raw.max_coeffs = max_coeffs;
            raw.raw_positions = raw_positions.data();  raw.raw_scales    = raw_scales.data();
            raw.raw_rotations = raw_rotations.data();  raw.raw_sh_coeffs = raw_sh.data();
            raw.raw_opacities = raw_opacities.data();

            std::memcpy(cam.view_matrix,     vm.f32(), 16 * sizeof(float));
            std::memcpy(cam.viewproj_matrix, pm.f32(), 16 * sizeof(float));
            cam.cam_pos[0] = cp.f32()[0];  cam.cam_pos[1] = cp.f32()[1];
            cam.cam_pos[2] = cp.f32()[2];
            cam.tan_fovx   = fov.f32()[0]; cam.tan_fovy   = fov.f32()[1];
            cam.width      = static_cast<int>(fov.f32()[2]);
            cam.height     = static_cast<int>(fov.f32()[3]);

            cfg.sh_degree      = sh_degree;  cfg.training       = true;
            cfg.eval_3D        = false;       cfg.tile_w         = 16;
            cfg.tile_h         = 16;          cfg.antialiasing   = false;
            cfg.scale_modifier = 1.0f;
            cfg.bg_color[0] = cfg.bg_color[1] = cfg.bg_color[2] = 0.0f;

            return true;
        } catch (...) {
            return false;
        }
    }
};

// Training config — must match Python dump's hyperparameters exactly.
VkTrainingConfig make_vk_tcfg() {
    VkTrainingConfig tcfg;
    tcfg.max_steps         = 30000;
    tcfg.pos_lr_init       = 1.6e-4f;
    tcfg.pos_lr_final      = 1.6e-6f;
    tcfg.sh_degree_max     = 0;        // lock SH degree to 0
    tcfg.sh_degree_warmup  = 100000;
    tcfg.lambda_dssim      = 0.0f;    // pure L1
    tcfg.opacity_reg       = 0.0f;
    tcfg.scale_reg         = 0.0f;
    tcfg.noise_lr          = 0.0f;
    tcfg.densify_from_step = 0;       // no densification
    return tcfg;
}

}  // namespace

// ---------------------------------------------------------------------------
// Test 1: Step1GradientAndLoss
//
// After exactly 1 step, compare:
//   - Loss against Python dump (< 1% rel_diff)
//   - Each gradient group L2 norm against Python dump (< 5% rel_diff)
//   - Each param group L2 norm after Adam against Python dump (< 1% rel_diff)
// ---------------------------------------------------------------------------

TEST(VkVsPyReference, Step1GradientAndLoss) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists()) GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    VkTrainingConfig tcfg = make_vk_tcfg();

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;  // lock SH degree to match Python dump

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, tcfg);
    trainer.enable_gradient_capture(true);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);

    // Run exactly 1 step.
    float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);

    ASSERT_FALSE(std::isnan(vk_loss)) << "VK loss is NaN after step 1";
    ASSERT_FALSE(std::isinf(vk_loss)) << "VK loss is Inf after step 1";

    // --- Load Python reference for step 1 ---
    const std::string pr = py_ref_dir();
    float py_loss = npy_scalar(pr + "/step_0001_loss.npy");

    auto py_grad_pos = npy_to_f32(load_npy(pr + "/step_0001_grad_pos.npy"));
    auto py_grad_sc  = npy_to_f32(load_npy(pr + "/step_0001_grad_sc.npy"));
    auto py_grad_rot = npy_to_f32(load_npy(pr + "/step_0001_grad_rot.npy"));
    auto py_grad_sh  = npy_to_f32(load_npy(pr + "/step_0001_grad_sh.npy"));
    auto py_grad_op  = npy_to_f32(load_npy(pr + "/step_0001_grad_op.npy"));

    auto py_raw_pos = npy_to_f32(load_npy(pr + "/step_0001_raw_pos.npy"));
    auto py_raw_sc  = npy_to_f32(load_npy(pr + "/step_0001_raw_sc.npy"));
    auto py_raw_rot = npy_to_f32(load_npy(pr + "/step_0001_raw_rot.npy"));
    auto py_raw_op  = npy_to_f32(load_npy(pr + "/step_0001_raw_op.npy"));

    // --- Loss comparison ---
    float loss_rd = rel_diff(py_loss, vk_loss);
    std::cout << "\n[Step 1 Loss]\n";
    std::cout << "  py_loss=" << py_loss << "  vk_loss=" << vk_loss
              << "  rel_diff=" << loss_rd << "\n";

    EXPECT_LT(loss_rd, 0.01f)
        << "Step-1 loss mismatch: Python=" << py_loss
        << " VK=" << vk_loss << " rel_diff=" << loss_rd;

    // --- Gradient norm comparison ---
    const std::vector<float>& vk_grad_pos = trainer.captured_grad_positions();
    const std::vector<float>& vk_grad_sc  = trainer.captured_grad_scales();
    const std::vector<float>& vk_grad_rot = trainer.captured_grad_rotations();
    const std::vector<float>& vk_grad_sh  = trainer.captured_grad_sh();
    const std::vector<float>& vk_grad_op  = trainer.captured_grad_opacities();

    struct GradGroup {
        const char* name;
        const std::vector<float>& py;
        const std::vector<float>& vk;
    };
    const GradGroup grad_groups[] = {
        { "positions", py_grad_pos, vk_grad_pos },
        { "scales",    py_grad_sc,  vk_grad_sc  },
        { "rotations", py_grad_rot, vk_grad_rot },
        { "sh",        py_grad_sh,  vk_grad_sh  },
        { "opacities", py_grad_op,  vk_grad_op  },
    };

    std::cout << "\n[Step 1 Gradient L2 norms]\n";
    std::cout << "Group       py_norm      vk_norm      rel_diff\n";
    std::cout << "----------  -----------  -----------  --------\n";
    for (const auto& gg : grad_groups) {
        float pn = l2_norm(gg.py);
        float vn = l2_norm(gg.vk);
        float rd = rel_diff(pn, vn);
        char buf[160];
        std::snprintf(buf, sizeof(buf), "%-10s  %.6e  %.6e  %.4f %s\n",
                      gg.name, pn, vn, rd, rd > 0.05f ? "MISMATCH" : "OK");
        std::cout << buf;
        EXPECT_LT(rd, 0.05f)
            << "Gradient " << gg.name << " norm mismatch: py=" << pn
            << " vk=" << vn << " rel_diff=" << rd;
    }

    // --- Post-Adam param norm comparison ---
    const RawGaussianParams& vk_p = trainer.raw_params();
    const int N = scene.N;

    struct ParamGroup {
        const char*   name;
        const std::vector<float>& py;
        const float*  vk;
        int           n;
    };
    const ParamGroup param_groups[] = {
        { "positions", py_raw_pos, vk_p.raw_positions, N * 3 },
        { "scales",    py_raw_sc,  vk_p.raw_scales,    N * 3 },
        { "rotations", py_raw_rot, vk_p.raw_rotations, N * 4 },
        { "opacities", py_raw_op,  vk_p.raw_opacities, N     },
    };

    std::cout << "\n[Step 1 Post-Adam Param L2 norms]\n";
    std::cout << "Group       py_norm      vk_norm      rel_diff\n";
    std::cout << "----------  -----------  -----------  --------\n";
    for (const auto& pg : param_groups) {
        float pn = l2_norm(pg.py);
        float vn = l2_norm(pg.vk, pg.n);
        float rd = rel_diff(pn, vn);
        char buf[160];
        std::snprintf(buf, sizeof(buf), "%-10s  %.6e  %.6e  %.4f %s\n",
                      pg.name, pn, vn, rd, rd > 0.01f ? "MISMATCH" : "OK");
        std::cout << buf;
        EXPECT_LT(rd, 0.01f)
            << "Param " << pg.name << " norm mismatch after step 1: py=" << pn
            << " vk=" << vn << " rel_diff=" << rd;
    }
}

// ---------------------------------------------------------------------------
// Test 2: ConvergenceTable100Steps
//
// Run VulkanTrainer for 100 steps. Assert:
//   (a) VK loss is finite and non-negative every step.
//   (b) Both VK and Python converge: loss at step 100 < 50% of step 1 loss.
//
// Per-step comparison table is printed for steps 1-10 and multiples of 10.
// Step-wise tolerance is NOT asserted — GPU/CPU FP accumulation diverges
// over many steps; this is expected and not a bug.
// ---------------------------------------------------------------------------

TEST(VkVsPyReference, ConvergenceTable100Steps) {
    VulkanContext ctx;
    if (!ctx.init()) GTEST_SKIP() << "No Vulkan compute device.";
    if (!py_ref_exists()) GTEST_SKIP() << "Python dump missing — run: python tools/dump_tiny_reference.py";

    TinyScene scene;
    ASSERT_TRUE(scene.load()) << "Could not load tiny golden fixture.";

    constexpr int N_STEPS = 100;

    VkTrainingConfig tcfg = make_vk_tcfg();

    RenderConfig rcfg = scene.cfg;
    rcfg.sh_degree = 0;  // lock SH degree to match Python dump

    VulkanTrainer trainer(ctx, scene.g, scene.raw,
                          scene.sh_degree, scene.W, scene.H, tcfg);

    const std::vector<float> target(static_cast<size_t>(scene.W) * scene.H * 3, 0.0f);

    std::vector<float> vk_losses(N_STEPS);
    std::vector<float> py_losses(N_STEPS);

    std::ostringstream log;
    log << "\nStep  py_loss      vk_loss      rel_diff\n";
    log << "----  -----------  -----------  --------\n";

    for (int s = 0; s < N_STEPS; ++s) {
        // Load Python loss for this step.
        char sname[256];
        std::snprintf(sname, sizeof(sname), "%s/step_%04d_loss.npy",
                      py_ref_dir().c_str(), s + 1);
        float py_loss = npy_scalar(sname);
        py_losses[static_cast<size_t>(s)] = py_loss;

        // Run VK step.
        float vk_loss = trainer.step(scene.cam, rcfg, target.data(), scene.W, scene.H);
        vk_losses[static_cast<size_t>(s)] = vk_loss;

        // (a) VK must never produce NaN/Inf/negative.
        ASSERT_FALSE(std::isnan(vk_loss)) << "VK loss is NaN at step " << (s + 1);
        ASSERT_FALSE(std::isinf(vk_loss)) << "VK loss is Inf at step " << (s + 1);
        ASSERT_GE(vk_loss, 0.0f)          << "VK loss negative at step " << (s + 1);

        // Print rows: steps 1-10 and every multiple of 10.
        if (s < 10 || (s + 1) % 10 == 0) {
            float rd = rel_diff(py_loss, vk_loss);
            char buf[128];
            std::snprintf(buf, sizeof(buf), "%4d  %.6e  %.6e  %.4f\n",
                          s + 1, py_loss, vk_loss, rd);
            log << buf;
        }
    }
    std::cout << log.str() << "\n";

    // (b) Both must converge: loss at step 100 < 50% of step 1 loss.
    EXPECT_LT(py_losses[N_STEPS - 1], py_losses[0] * 0.5f)
        << "Python did not converge in 100 steps: init=" << py_losses[0]
        << " final=" << py_losses[N_STEPS - 1];
    EXPECT_LT(vk_losses[N_STEPS - 1], vk_losses[0] * 0.5f)
        << "VK did not converge in 100 steps: init=" << vk_losses[0]
        << " final=" << vk_losses[N_STEPS - 1];
}
