// test_relocation.cpp — Phase 1 of MCMC densification port.
//
// Verifies mcmc::compute_relocation against ground truth generated by
// tools/generate_relocation_ground_truth.py (which mirrors AAA-Gaussians
// utils.cu::compute_relocation). All-CPU test — no Vulkan dependency.

#include "relocation.h"

#include <gtest/gtest.h>

// ============================================================
// Auto-generated by tools/generate_relocation_ground_truth.py
// Mirrors AAA-Gaussians compute_relocation kernel (utils.cu).
// DO NOT EDIT BY HAND — re-run the script if formula changes.
// ============================================================

struct ReloCase {
    float opacity_old;
    float scale_old[3];
    int   N;
    float opacity_new_expected;
    float scale_new_expected[3];
};

static const ReloCase kReloIsoCases[] = {
    { 0.100000f, { 0.050000f, 0.050000f, 0.050000f }, 2, 0.05131670f, { 0.04961730f, 0.04961730f, 0.04961730f } },
    { 0.100000f, { 0.050000f, 0.050000f, 0.050000f }, 3, 0.03451062f, { 0.04949068f, 0.04949068f, 0.04949068f } },
    { 0.100000f, { 0.050000f, 0.050000f, 0.050000f }, 5, 0.02085164f, { 0.04938973f, 0.04938973f, 0.04938973f } },
    { 0.500000f, { 0.100000f, 0.100000f, 0.100000f }, 2, 0.29289322f, { 0.09521520f, 0.09521520f, 0.09521520f } },
    { 0.500000f, { 0.100000f, 0.100000f, 0.100000f }, 3, 0.20629947f, { 0.09368818f, 0.09368818f, 0.09368818f } },
    { 0.500000f, { 0.100000f, 0.100000f, 0.100000f }, 5, 0.12944944f, { 0.09249079f, 0.09249079f, 0.09249079f } },
    { 0.880000f, { 0.005000f, 0.005000f, 0.005000f }, 2, 0.65358984f, { 0.00437760f, 0.00437760f, 0.00437760f } },
    { 0.880000f, { 0.005000f, 0.005000f, 0.005000f }, 3, 0.50675759f, { 0.00418790f, 0.00418790f, 0.00418790f } },
    { 0.880000f, { 7.390000f, 7.390000f, 7.390000f }, 2, 0.65358984f, { 6.47008590f, 6.47008590f, 6.47008590f } },
    { 0.880000f, { 7.390000f, 7.390000f, 7.390000f }, 3, 0.50675759f, { 6.18971904f, 6.18971904f, 6.18971904f } },
    { 0.990000f, { 0.100000f, 0.100000f, 0.100000f }, 2, 0.90000000f, { 0.08066859f, 0.08066859f, 0.08066859f } },
    { 0.990000f, { 0.100000f, 0.100000f, 0.100000f }, 5, 0.60189283f, { 0.07001766f, 0.07001766f, 0.07001766f } },
    { 0.001000f, { 0.005000f, 0.005000f, 0.005000f }, 2, 0.00050013f, { 0.00499963f, 0.00499963f, 0.00499963f } },
    { 0.500000f, { 0.100000f, 0.100000f, 0.100000f }, 1, 0.50000000f, { 0.10000000f, 0.10000000f, 0.10000000f } },
    { 0.500000f, { 0.100000f, 0.100000f, 0.100000f }, 50, 0.01376730f, { 0.09090826f, 0.09090826f, 0.09090826f } },
};

static const ReloCase kReloAnisoCases[] = {
    { 0.500000f, { 0.100000f, 0.200000f, 0.300000f }, 3, 0.20629947f, { 0.09368818f, 0.18737635f, 0.28106453f } },
    { 0.880000f, { 0.005000f, 0.010000f, 0.015000f }, 2, 0.65358984f, { 0.00437760f, 0.00875519f, 0.01313279f } },
};

// ============================================================
// Tests
// ============================================================

TEST(McmcRelocation, IsotropicCases) {
    for (const auto& c : kReloIsoCases) {
        float op_new = 0.0f;
        float sc_new[3] = {0.0f, 0.0f, 0.0f};
        mcmc::compute_relocation(c.opacity_old, c.scale_old, c.N, op_new, sc_new);
        EXPECT_NEAR(op_new, c.opacity_new_expected, 1e-5f) << "N=" << c.N;
        for (int j = 0; j < 3; ++j) {
            EXPECT_NEAR(sc_new[j], c.scale_new_expected[j], 1e-5f)
                << "N=" << c.N << " axis " << j;
        }
    }
}

TEST(McmcRelocation, AnisotropicCases) {
    for (const auto& c : kReloAnisoCases) {
        float op_new = 0.0f;
        float sc_new[3] = {0.0f, 0.0f, 0.0f};
        mcmc::compute_relocation(c.opacity_old, c.scale_old, c.N, op_new, sc_new);
        EXPECT_NEAR(op_new, c.opacity_new_expected, 1e-5f) << "N=" << c.N;
        for (int j = 0; j < 3; ++j) {
            EXPECT_NEAR(sc_new[j], c.scale_new_expected[j], 1e-5f)
                << "N=" << c.N << " axis " << j;
        }
    }
}

TEST(McmcRelocation, NEqualOneIsIdentity) {
    float scale[3] = {0.123f, 0.456f, 0.789f};
    float op_new = 0.0f;
    float sc_new[3] = {0.0f, 0.0f, 0.0f};
    mcmc::compute_relocation(0.5f, scale, 1, op_new, sc_new);
    EXPECT_NEAR(op_new, 0.5f, 1e-6f);
    for (int j = 0; j < 3; ++j) {
        EXPECT_NEAR(sc_new[j], scale[j], 1e-6f) << "axis " << j;
    }
}

TEST(McmcRelocation, ClampsLargeN) {
    // N > N_MAX-1 should clamp; behavior matches N=N_MAX-1.
    float scale[3] = {0.1f, 0.1f, 0.1f};
    float op_a = 0.0f, op_b = 0.0f;
    float sc_a[3] = {0.0f, 0.0f, 0.0f};
    float sc_b[3] = {0.0f, 0.0f, 0.0f};
    mcmc::compute_relocation(0.5f, scale, 100, op_a, sc_a);
    mcmc::compute_relocation(0.5f, scale, mcmc::N_MAX - 1, op_b, sc_b);
    EXPECT_FLOAT_EQ(op_a, op_b);
    for (int j = 0; j < 3; ++j) {
        EXPECT_FLOAT_EQ(sc_a[j], sc_b[j]) << "axis " << j;
    }
}

TEST(McmcRelocation, ClampsSmallN) {
    // N < 1 should clamp to 1 (identity).
    float scale[3] = {0.123f, 0.456f, 0.789f};
    float op_new = 0.0f;
    float sc_new[3] = {0.0f, 0.0f, 0.0f};
    mcmc::compute_relocation(0.5f, scale, 0, op_new, sc_new);
    EXPECT_NEAR(op_new, 0.5f, 1e-6f);
    for (int j = 0; j < 3; ++j) {
        EXPECT_NEAR(sc_new[j], scale[j], 1e-6f) << "axis " << j;
    }
}
